try run successfully

diff --git a/.github/workflows/backend-ci-cd.yml b/.github/workflows/backend-ci-cd.yml
--- a/.github/workflows/backend-ci-cd.yml
+++ b/.github/workflows/backend-ci-cd.yml
@@ -22,14 +22,20 @@ jobs:
       - name: Build with Maven
         run: mvn clean package -DskipTests
 
-      - name: Deploy to server using sshpass
+      - name: cp .jar to server
         run: sshpass -p ${{ secrets.PASSWORD }} scp -o StrictHostKeyChecking=no -v ./target/backend-0.0.1-SNAPSHOT.jar ubuntu@150.158.39.251:/home/ubuntu/phase2/
 
       # Restart the JAR file
-      - name: kill pre pid
-        run: sshpass -p ${{ secrets.PASSWORD }} ssh  -vvv -o PasswordAuthentication=yes ubuntu@150.158.39.251 'pkill -f backend-0.0.1-SNAPSHOT.jar'
+      - name: Check if process exists
+        run: |
+          if ! sshpass -p ${{ secrets.PASSWORD }} ssh -o PasswordAuthentication=yes ubuntu@150.158.39.251 "pgrep -f backend-0.0.1-SNAPSHOT.jar" > /dev/null; then
+            echo "Process not found. Proceeding with restart."
+          else
+            sshpass -p ${{ secrets.PASSWORD }} ssh -o PasswordAuthentication=yes ubuntu@150.158.39.251 'pkill -f backend-0.0.1-SNAPSHOT.jar'
+          fi
 
-      - name: start new JAR file
-        run: sshpass -p ${{ secrets.PASSWORD }} ssh  -vvv -o PasswordAuthentication=yes ubuntu@150.158.39.251 'nohup java -jar /home/ubuntu/phase2/backend-0.0.1-SNAPSHOT.jar &'
+      - name: Start new JAR file
+        run: sshpass -p ${{ secrets.PASSWORD }} ssh -o PasswordAuthentication=yes ubuntu@150.158.39.251 'nohup java -jar /home/ubuntu/phase2/backend-0.0.1-SNAPSHOT.jar &'
+
 
 
